[package]
name = "vara-man-game"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear", rev = "946ac47" }
hashbrown = "0.14"
vara-man-io = { path = "../io" }

[dev-dependencies]
gstd = { git = "https://github.com/gear-tech/gear", features = ["debug"], rev = "946ac47" }
gtest = { git = "https://github.com/gear-tech/gear", rev = "946ac47" }
subxt = { version = "0.30", default-features = false }
gclient = { git = "https://github.com/gear-tech/gear", rev = "946ac47" }
tokio = "1"
blake2-rfc = { version = "0.2.18", default-features = false }

[build-dependencies]
vara-man-io = { path = "../io" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear", rev = "946ac47" }

[features]
# Used for inserting constants with WASM binaries (NOT paths) of the contract in
# the root crate. Usually these constants used in gclient tests instead of
# strings with paths to the binaries in the "target" directory. If you don't
# like this approach or don't use gclient tests, you can freely remove this
# feature from here and from the rest of the code.
binary-vendor = []
